"use client"

import { useMemo, useState } from "react"

type View = "briefing" | "entities" | "network" | "analytics" | "audit"
type Suspect = { name: string; id: string; role: string; risk: number; links: number; community: string; status: string }
const suspects: Suspect[] = [
  { name: "Arjun Mehta", id: "PER-00482", role: "Network Kingpin", risk: 98, links: 64, community: "C-07 / Red Meridian", status: "ACTIVE" },
  { name: "Vikram Reddy", id: "PER-00317", role: "Financial Controller", risk: 91, links: 42, community: "C-07 / Red Meridian", status: "WATCH" },
  { name: "Nisha Kapoor", id: "PER-00891", role: "Logistics Coordinator", risk: 86, links: 37, community: "C-12 / North Star", status: "ACTIVE" },
  { name: "Rohan Das", id: "PER-00204", role: "Field Operative", risk: 78, links: 29, community: "C-07 / Red Meridian", status: "MONITOR" },
]
const alerts = [["FINANCIAL", "Structuring pattern detected", "12 transfers · ₹48.2L", "2m ago", "high"], ["TELECOM", "Communication burst anomaly", "PER-00482 ↔ 7 nodes", "18m ago", "medium"], ["LOCATION", "Convergence at flagged site", "Dockyard Sector 4", "41m ago", "high"], ["IDENTITY", "New KYC ownership link", "ACC_4418 → PER-00317", "1h ago", "low"]]
const nav: { id: View; label: string; icon: string }[] = [{ id: "briefing", label: "Operational Briefing", icon: "◈" }, { id: "entities", label: "Entity Search", icon: "⌕" }, { id: "network", label: "Network Explorer", icon: "⌘" }, { id: "analytics", label: "Syndicate Analytics", icon: "◒" }, { id: "audit", label: "Chain of Custody", icon: "▣" }]

export default function Home() {
  const [view, setView] = useState<View>("briefing")
  const [selected, setSelected] = useState<Suspect | null>(suspects[0])
  const [query, setQuery] = useState("")
  const [sidebar, setSidebar] = useState(true)
  const filtered = useMemo(() => suspects.filter((s) => `${s.name} ${s.id} ${s.role}`.toLowerCase().includes(query.toLowerCase())), [query])
  const title = nav.find((item) => item.id === view)?.label ?? "Operational Briefing"
  return <main className="app-shell">
    <aside className={`sidebar ${sidebar ? "" : "collapsed"}`}>
      <div className="brand"><div className="brand-mark">N</div>{sidebar && <div><div className="brand-name">NEXUS<span>/AI</span></div><div className="brand-sub">INTELLIGENCE OPERATIONS</div></div>}</div>
      {sidebar && <div className="case-file"><span className="eyebrow">ACTIVE CASE FILE</span><strong>OPERATION MERIDIAN</strong><span className="case-meta"><i className="pulse" /> CLASSIFIED / SIGMA-7</span></div>}
      <nav className="nav-list">{nav.map((item) => <button key={item.id} onClick={() => setView(item.id)} className={`nav-item ${view === item.id ? "active" : ""}`}><span className="nav-icon">{item.icon}</span>{sidebar && <span>{item.label}</span>}</button>)}</nav>
      {sidebar && <div className="sidebar-bottom"><div className="system-card"><span className="eyebrow">SYSTEM STATUS</span><div className="status-row"><i className="status-dot" />All systems nominal</div><div className="status-line"><span>Graph engine</span><strong>99.98%</strong></div><div className="status-line"><span>Last sync</span><strong>00:02:14</strong></div></div><div className="profile"><div className="avatar">AS</div><div><strong>ANANYA SHARMA</strong><span>Senior Investigator</span></div></div></div>}
    </aside>
    <section className="workspace">
      <header className="topbar"><button className="icon-btn" onClick={() => setSidebar(!sidebar)}>☰</button><div className="crumb"><span>CASE FILE</span><b>/</b><strong>{title.toUpperCase()}</strong></div><div className="top-actions"><div className="live-status"><i className="pulse" />LIVE FEED <span>•</span> 14:32:08 IST</div><button className="icon-btn">◌</button><button className="icon-btn">⚙</button></div></header>
      <div className="commandbar"><div className="search"><span>⌕</span><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search entities, aliases, accounts, locations..." /><kbd>⌘ K</kbd></div><button className="filter-btn">FILTERS <span>03</span></button><button className="refresh">↻ REFRESH</button></div>
      <div className="content">{view === "briefing" && <Briefing filtered={filtered} selected={selected} setSelected={setSelected} />}{view === "entities" && <Entities filtered={filtered} setSelected={setSelected} />}{view === "network" && <Network selected={selected} />}{view === "analytics" && <Analytics />}{view === "audit" && <Audit />}</div>
    </section>
    {selected && view !== "audit" && <aside className="detail-drawer"><button className="drawer-close" onClick={() => setSelected(null)}>×</button><span className="eyebrow">SELECTED ENTITY</span><div className="dossier-head"><div className="large-avatar">{selected.name.split(" ").map((n) => n[0]).join("")}</div><div><h2>{selected.name}</h2><p>{selected.id} · {selected.role}</p></div></div><div className="risk-banner"><span>RISK SCORE</span><strong>{selected.risk}<small>/100</small></strong><div className="risk-bar"><i style={{ width: `${selected.risk}%` }} /></div></div><div className="detail-grid"><div><span>COMMUNITY</span><strong>{selected.community}</strong></div><div><span>LINKED NODES</span><strong>{selected.links}</strong></div><div><span>LAST ACTIVITY</span><strong>14:27 IST</strong></div><div><span>CONFIDENCE</span><strong>94.8%</strong></div></div><div className="drawer-section"><div className="section-title">RECENT SIGNALS <span>VIEW ALL</span></div>{alerts.slice(0, 3).map((a) => <div className="signal" key={a[1]}><i className={`signal-dot ${a[4]}`} /><div><strong>{a[1]}</strong><span>{a[2]} · {a[3]}</span></div></div>)}</div><button className="primary-action">OPEN FULL DOSSIER <span>↗</span></button></aside>}
  </main>
}

function Briefing({ filtered, selected, setSelected }: { filtered: Suspect[]; selected: Suspect | null; setSelected: (s: Suspect) => void }) {
  return <><div className="page-heading"><div><span className="eyebrow">THURSDAY, 18 SEPTEMBER 2025 · SHIFT ALPHA</span><h1>Operational Briefing</h1><p>Live intelligence overview for Operation Meridian.</p></div><div className="heading-actions"><button className="secondary">↥ EXPORT BRIEF</button><button className="primary">+ NEW INVESTIGATION</button></div></div><div className="metrics"><Metric label="ACTIVE TARGETS" value="247" delta="+12" tone="cyan" icon="◎" /><Metric label="HIGH-RISK ENTITIES" value="18" delta="+3" tone="red" icon="△" /><Metric label="NETWORK LINKS" value="1,842" delta="+8.4%" tone="blue" icon="⌘" /><Metric label="OPEN ALERTS" value="32" delta="−5" tone="amber" icon="◉" /></div><div className="brief-grid"><section className="panel graph-panel"><PanelHead label="TOPOLOGY OVERVIEW" title="Network Activity Map" /><GraphCanvas /><div className="legend"><span><i className="legend-dot person" />PERSON</span><span><i className="legend-dot org" />ORGANIZATION</span><span><i className="legend-dot account" />ACCOUNT</span><span><i className="legend-line" />SUSPICIOUS LINK</span></div></section><section className="panel alerts-panel"><PanelHead label="BEHAVIORAL INTELLIGENCE" title="Active Alerts" />{alerts.map((a) => <div className="alert-row" key={a[1]}><div className={`alert-icon ${a[4]}`}>{a[0][0]}</div><div className="alert-copy"><strong>{a[1]}</strong><span>{a[2]}</span></div><time>{a[3]}</time></div>)}</section></div><section className="panel table-panel"><PanelHead label="RISK ENGINE · UPDATED 14:30 IST" title="High-Risk Core" /><div className="table-wrap"><table><thead><tr><th>ENTITY</th><th>ROLE / COMMUNITY</th><th>RISK SCORE</th><th>LINKS</th><th>STATUS</th></tr></thead><tbody>{filtered.map((s) => <tr key={s.id} onClick={() => setSelected(s)} className={selected?.id === s.id ? "selected-row" : ""}><td><div className="entity-cell"><div className="mini-avatar">{s.name.split(" ").map((n) => n[0]).join("")}</div><div><strong>{s.name}</strong><span>{s.id}</span></div></div></td><td><strong>{s.role}</strong><span className="muted">{s.community}</span></td><td><div className="score"><strong className={s.risk > 90 ? "critical" : "high"}>{s.risk}</strong><div className="mini-bar"><i style={{ width: `${s.risk}%` }} /></div></div></td><td className="mono">{s.links}</td><td><span className={`status ${s.status.toLowerCase()}`}>{s.status}</span></td></tr>)}</tbody></table></div></section></>
}

function PanelHead({ label, title }: { label: string; title: string }) { return <div className="panel-head"><div><span className="eyebrow">{label}</span><h3>{title} <b className="count">LIVE</b></h3></div><button className="ghost">VIEW ALL →</button></div> }
function Metric({ label, value, delta, tone, icon }: { label: string; value: string; delta: string; tone: string; icon: string }) { return <div className="metric"><div className={`metric-icon ${tone}`}>{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{delta} <em>vs last shift</em></small></div><div className="sparkline">╱╲╱╲╱╲</div></div> }
function GraphCanvas() { return <div className="graph-canvas"><div className="graph-grid" /><div className="graph-lines"><i className="line l1" /><i className="line l2" /><i className="line l3" /><i className="line l4" /></div><div className="graph-node kingpin">AM</div><div className="graph-node n2">VR</div><div className="graph-node n3">NK</div><div className="graph-node n4">RD</div><div className="graph-node n5 org">RM</div><div className="graph-node n6 account">₹</div><div className="map-label label-a">PER-00482</div><div className="map-label label-b">C-07 · RED MERIDIAN</div><div className="map-coords">LAT 18.5204° N<br />LNG 73.8567° E</div></div> }
function Entities({ filtered, setSelected }: { filtered: Suspect[]; setSelected: (s: Suspect) => void }) { return <><div className="page-heading"><div><span className="eyebrow">ENTITY RESOLUTION ENGINE</span><h1>Entity Search</h1><p>Search across the unified intelligence graph.</p></div></div><section className="panel table-panel"><div className="table-wrap"><table><thead><tr><th>ENTITY</th><th>TYPE</th><th>RISK</th><th>COMMUNITY</th><th>LAST SEEN</th></tr></thead><tbody>{filtered.map((s) => <tr key={s.id} onClick={() => setSelected(s)}><td><div className="entity-cell"><div className="mini-avatar">{s.name.split(" ").map((n) => n[0]).join("")}</div><div><strong>{s.name}</strong><span>{s.id}</span></div></div></td><td>PERSON</td><td><span className={`status ${s.risk > 90 ? "critical" : "high"}`}>{s.risk} / 100</span></td><td>{s.community}</td><td className="mono">TODAY, 14:27</td></tr>)}</tbody></table></div></section></> }
function Network({ selected }: { selected: Suspect | null }) { return <><div className="page-heading"><div><span className="eyebrow">NEO4J GRAPH INTELLIGENCE</span><h1>Network Explorer</h1><p>Interactive topology for {selected?.community ?? "all active communities"}.</p></div><button className="primary">RUN PATHFINDER</button></div><div className="panel immersive"><GraphCanvas /><div className="explorer-controls">LAYOUT <strong>FORCE-DIRECTED⌄</strong> EDGES <strong>ALL TYPES⌄</strong> DEPTH <strong>3 HOPS⌄</strong></div></div></> }
function Analytics() { return <><div className="page-heading"><div><span className="eyebrow">PATTERN DISCOVERY ENGINE</span><h1>Syndicate Analytics</h1><p>Signals surfaced from 30 days of multi-modal evidence.</p></div><button className="primary">GENERATE REPORT ↗</button></div><div className="analytics-grid"><div className="panel analytic-card wide"><span className="eyebrow">COMMUNICATION BURSTS</span><h3>Call volume by hour</h3><div className="bars">{[28, 45, 38, 66, 52, 80, 62, 91, 70, 54, 76, 43, 68, 36, 58, 84].map((n, i) => <i key={i} style={{ height: `${n}%` }} />)}</div></div><div className="panel analytic-card"><span className="eyebrow">RISK DISTRIBUTION</span><h3>18 high-risk entities</h3><div className="donut"><strong>73<small>%</small></strong></div><div className="donut-key">CRITICAL 6 · HIGH 12</div></div></div></> }
function Audit() { return <><div className="page-heading"><div><span className="eyebrow">CRYPTOGRAPHIC EVIDENCE INTEGRITY</span><h1>Chain of Custody</h1><p>Immutable access ledger for evidentiary review.</p></div><div className="verified"><i />CHAIN VERIFIED</div></div><section className="panel table-panel"><PanelHead label="APPEND-ONLY LEDGER" title="Evidence Access Log" /><div className="table-wrap"><table><thead><tr><th>BLOCK</th><th>TIMESTAMP</th><th>ACTOR / ACTION</th><th>ENTITY ACCESSED</th><th>STATUS</th></tr></thead><tbody>{["A9F2C881", "A9F2C880", "A9F2C87F", "A9F2C87E"].map((hash, i) => <tr key={hash}><td className="mono">#{18402 - i}</td><td className="mono">18 SEP · 14:{32 - i}8:04</td><td><strong>ANANYA SHARMA</strong><span className="muted">VIEW_ENTITY</span></td><td>{`PER-00${482 - i * 17}`}</td><td><span className="status active">VERIFIED</span></td></tr>)}</tbody></table></div></section></> }
